### ISSUE TITLE
Should we add <ORDER-TREE? REVERSE-DEFINED>? Not so fast...

### ISSUE THREAD

**Issue by eriktorbjorn** [the-infocom-files/zork1-mini#4]
At some point in late 1985, it appears the behavior of ZILCH changed in how it generates the object tree. ZILF, by default, emulates the older behavior. Usually the object trees aren't identical, but the children of an object are generally ordered the same way as in the original release.

In practical terms, Ballyhoo and all subsequent games use a different tree ordering, and this can potentially cause problems when compiling the game with ZILF. For most games the solution seems pretty clear: Add ```<ORDER-TREE? REVERSE-DEFINED>```.

But here is a conundrum, because the game has been released in so many different forms: We have MDL Zork, Zork I, Zork I Solid Gold, and now Mini-Zork I:

Let's use the Kitchen as an example. Here's MDL Zork (1/24/78), running at its.pdp10.se. See https://eblong.com/infocom/#zorkmdl for instructions.

```zil
>LOOK
You are in the kitchen of the white house.  A table seems to have
been used recently for the preparation of food.  A passage leads to
the west and a dark staircase can be seen leading upward.  To the
east is a small window which is open.
On the table is an elongated brown sack, smelling of hot peppers.
A bottle is sitting on the table.
The glass bottle contains:
 A quantity of water
```

Here's the official release of Zork I:

```
>LOOK
Kitchen
You are in the kitchen of the white house. A table seems to have been used
recently for the preparation of food. A passage leads to the west and a dark
staircase can be seen leading upward. A dark chimney leads down and to the east
is a small window which is open.
On the table is an elongated brown sack, smelling of hot peppers.
A bottle is sitting on the table.
The glass bottle contains:
  A quantity of water
```

Here's the official Solid Gold version of Zork I. This is where things start to get different:

```
>LOOK
Kitchen
You are in the kitchen of the white house. A table seems to have been used
recently for the preparation of food. A passage leads to the west and a dark
staircase can be seen leading upward. A dark chimney leads down and to the east
is a small window which is open.
A bottle is sitting on the table.
The glass bottle contains:
  A quantity of water
On the table is an elongated brown sack, smelling of hot peppers.
```

Here's the official Mini-Zork I:

```
>LOOK
Kitchen
You are in the kitchen of the white house. A table has been used recently for
the preparation of food. A passage leads west and a dark staircase leads upward.
A chimney leads down and to the east is a small window which is open.
A bottle is sitting on the table.
The glass bottle contains:
  A quantity of water
On the table is an elongated brown sack, smelling of hot peppers.
```

Finally, here's Mini-Zork I when compiled with ZILF:

```
>LOOK
Kitchen
You are in the kitchen of the white house. A table has been used recently for
the preparation of food. A passage leads west and a dark staircase leads upward.
A chimney leads down and to the east is a small window which is open.
On the table is an elongated brown sack, smelling of hot peppers.
A bottle is sitting on the table.
The glass bottle contains:
  A quantity of water
```

So with ZILF, the objects are listed in the same order as in MDL Zork and Zork I, not as in Zork I Solid Gold or the official Mini-Zork I.

We can emulate the official version by adding ```<ORDER-TREE? REVERSE-DEFINED>```. But which best preserves the originial intention?

**Comment by AlexProudfoot** [comment]
I don't think the change in object order was deliberate. I can't prove it for a fact but, since there is no documentation to the contrary, I'm going to assume it's an unintended consequence of a change in ZILCH. No action required.
